// Build src/game/data/shapes.js from the item catalog.
//   node tools/build-shapes.mjs            write shapes.js
//   node tools/build-shapes.mjs --show     also print every shape as ASCII
import { writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";
import { decodePng } from "./png.mjs";
import { deriveShape, spriteBBox, ascii } from "./derive.mjs";
import { ITEMS } from "../src/game/data/items.js";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");
const spriteDir = join(root, "src/assets/items/packitup_cropped_assets/normalized");
const show = process.argv.includes("--show");

const out = {};
for (const [id, it] of Object.entries(ITEMS)) {
  const img = decodePng(join(spriteDir, it.file + ".png"));
  let shape;
  if (it.shape) {
    const rows = it.shape;
    const cells = [];
    rows.forEach((row, y) => [...row].forEach((ch, x) => ch === "#" && cells.push([x, y])));
    const bb = spriteBBox(img);
    shape = { w: rows[0].length, h: rows.length, cells, bbox: [bb.x, bb.y, bb.w, bb.h] };
  } else {
    shape = deriveShape(img, it.size, it.t ?? 0.34);
  }
  out[id] = shape;
  if (show) {
    const tag = `${it.weight === 3 ? " HEAVY" : ""}${it.fragile ? " fragile" : ""}`;
    console.log(`${id} (${it.name}) size ${it.size} → ${shape.w}x${shape.h}, ${shape.cells.length} cells${tag}`);
    console.log(ascii(shape).replace(/^/gm, "    "));
  }
}
writeFileSync(join(root, "src/game/data/shapes.js"), "// generated by tools/build-shapes.mjs — do not edit\nexport default " + JSON.stringify(out) + ";\n");
console.log(`wrote ${Object.keys(out).length} shapes`);
